### ISSUE TITLE
 Unhandled error detected in the injected client.js script.

### ISSUE THREAD

**Issue by huynhducloi00** [dart-lang/webdev#1146] opened 2020-10-13 10:51 UTC
client.js:3282 Unhandled error detected in the injected client.js script.

You can disable this script in webdev by passing --no-injected-client if it
is preventing your app from loading, but note that this will also prevent
all debugging and hot reload/restart functionality from working.

The original error is below, please file an issue at
https://github.com/dart-lang/webdev/issues/new and attach this output:

NoSuchMethodError: method not found: 'get$digestsPath' (J.getInterceptor$x(...).get$digestsPath is not a function)
TypeError: J.getInterceptor$x(...).get$digestsPath is not a function
    at Object.get$digestsPath$x (http://localhost:53884/dwds/src/injected/client.js:3495:43)
    at http://localhost:53884/dwds/src/injected/client.js:22811:60
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:53884/dwds/src/injected/client.js:3793:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:53884/dwds/src/injected/client.js:11010:12)
    at Object._asyncStartSync (http://localhost:53884/dwds/src/injected/client.js:3757:20)
    at RequireRestarter._getDigests$0 (http://localhost:53884/dwds/src/injected/client.js:22823:16)
    at http://localhost:53884/dwds/src/injected/client.js:22838:48
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:53884/dwds/src/injected/client.js:3793:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:53884/dwds/src/injected/client.js:11010:12)
    at Object._asyncStartSync (http://localhost:53884/dwds/src/injected/client.js:3757:20)
    at RequireRestarter._initialize$0 (http://localhost:53884/dwds/src/injected/client.js:22846:16)
    at http://localhost:53884/dwds/src/injected/client.js:8578:45
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:53884/dwds/src/injected/client.js:3793:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:53884/dwds/src/injected/client.js:11010:12)
    at Object._asyncStartSync (http://localhost:53884/dwds/src/injected/client.js:3757:20)
    at Object.RequireRestarter_create (http://localhost:53884/dwds/src/injected/client.js:8590:16)
    at http://localhost:53884/dwds/src/injected/client.js:22398:38
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:53884/dwds/src/injected/client.js:3793:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:53884/dwds/src/injected/client.js:11010:12)
    at _awaitOnObject_closure.call$1 (http://localhost:53884/dwds/src/injected/client.js:10996:32)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:53884/dwds/src/injected/client.js:4118:18)
    at _CustomZone.runUnary$2$2 (http://localhost:53884/dwds/src/injected/client.js:12315:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:53884/dwds/src/injected/client.js:11376:51)
    at Object._Future__propagateToListeners (http://localhost:53884/dwds/src/injected/client.js:3905:93)
    at _Future._complete$1 (http://localhost:53884/dwds/src/injected/client.js:11200:11)
    at Object._cancelAndValue (http://localhost:53884/dwds/src/injected/client.js:4060:16)
    at Stream_first_closure0.call$1 (http://localhost:53884/dwds/src/injected/client.js:11468:9)
    at _EventStreamSubscription_onData_closure.call$1 (http://localhost:53884/dwds/src/injected/client.js:17396:30)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:53884/dwds/src/injected/client.js:4124:16)
    at _CustomZone.runUnary$2$2 (http://localhost:53884/dwds/src/injected/client.js:12315:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:53884/dwds/src/injected/client.js:12247:14)
    at _CustomZone_bindUnaryCallbackGuarded_closure.call$1 (http://localhost:53884/dwds/src/injected/client.js:12450:25)
    at invokeClosure (http://localhost:53884/dwds/src/injected/client.js:1204:26)
    at EventSource.<anonymous> (http://localhost:53884/dwds/src/injected/client.js:1223:18)

**Comment by hparicha** [comment] 2020-10-13 15:17
Seeing the same as of this a.m.

**Comment by grouma** [comment] 2020-10-13 15:27
Dupe of https://github.com/dart-lang/webdev/issues/1133

**Closed by grouma** 2020-10-13 15:27 UTC
