### ISSUE TITLE
Flutter web is stuck

### ISSUE THREAD

**Issue by hayumi365** [dart-lang/webdev#1132] opened 2020-10-07 10:32 UTC
method not found: 'get$digestsPath' (J.getInterceptor$x(...).get$digestsPath is not a function)
TypeError: J.getInterceptor$x(...).get$digestsPath is not a function
    at Object.get$digestsPath$x (http://localhost:8686/dwds/src/injected/client.js:3507:43)
    at http://localhost:8686/dwds/src/injected/client.js:22732:60
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8686/dwds/src/injected/client.js:3802:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8686/dwds/src/injected/client.js:10996:12)
    at Object._asyncStartSync (http://localhost:8686/dwds/src/injected/client.js:3766:20)
    at RequireRestarter._getDigests$0 (http://localhost:8686/dwds/src/injected/client.js:22744:16)
    at http://localhost:8686/dwds/src/injected/client.js:22759:48
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8686/dwds/src/injected/client.js:3802:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8686/dwds/src/injected/client.js:10996:12)
    at Object._asyncStartSync (http://localhost:8686/dwds/src/injected/client.js:3766:20)
    at RequireRestarter._initialize$0 (http://localhost:8686/dwds/src/injected/client.js:22767:16)
    at http://localhost:8686/dwds/src/injected/client.js:8572:45
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8686/dwds/src/injected/client.js:3802:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8686/dwds/src/injected/client.js:10996:12)
    at Object._asyncStartSync (http://localhost:8686/dwds/src/injected/client.js:3766:20)
    at Object.RequireRestarter_create (http://localhost:8686/dwds/src/injected/client.js:8584:16)
    at http://localhost:8686/dwds/src/injected/client.js:22319:38
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8686/dwds/src/injected/client.js:3802:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8686/dwds/src/injected/client.js:10996:12)
    at _awaitOnObject_closure.call$1 (http://localhost:8686/dwds/src/injected/client.js:10982:32)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:8686/dwds/src/injected/client.js:4130:18)
    at _CustomZone.runUnary$2$2 (http://localhost:8686/dwds/src/injected/client.js:12301:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:8686/dwds/src/injected/client.js:11362:51)
    at Object._Future__propagateToListeners (http://localhost:8686/dwds/src/injected/client.js:3914:93)
    at _Future._complete$1 (http://localhost:8686/dwds/src/injected/client.js:11186:11)
    at Object._cancelAndValue (http://localhost:8686/dwds/src/injected/client.js:4069:16)
    at Stream_first_closure0.call$1 (http://localhost:8686/dwds/src/injected/client.js:11454:9)
    at _EventStreamSubscription_onData_closure.call$1 (http://localhost:8686/dwds/src/injected/client.js:17309:30)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:8686/dwds/src/injected/client.js:4136:16)
    at _CustomZone.runUnary$2$2 (http://localhost:8686/dwds/src/injected/client.js:12301:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:8686/dwds/src/injected/client.js:12233:14)
    at _CustomZone_bindUnaryCallbackGuarded_closure.call$1 (http://localhost:8686/dwds/src/injected/client.js:12436:25)
    at invokeClosure (http://localhost:8686/dwds/src/injected/client.js:1204:26)
    at EventSource.<anonymous> (http://localhost:8686/dwds/src/injected/client.js:1223:18)

**Comment by grouma** [comment] 2020-10-07 20:07
Dupe of https://github.com/dart-lang/webdev/issues/1133

**Closed by grouma** 2020-10-07 20:07 UTC
