### ISSUE TITLE
Found 107 files excluded from sound null safety in dwds/

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#1636] opened 2022-06-03 19:21 UTC
Found 107 files excluded from sound null safety in dwds/:

```
dwds/lib/src/utilities/sdk_configuration.dart:5:// @dart=2.9
dwds/debug_extension/tool/copy_builder.dart:5:// @dart = 2.9
dwds/debug_extension/web/background.dart:5:// @dart = 2.9
dwds/lib/dwds.dart:5:// @dart = 2.9
dwds/lib/src/connections/app_connection.dart:5:// @dart = 2.9
dwds/lib/src/connections/debug_connection.dart:5:// @dart = 2.9
dwds/lib/src/debugging/classes.dart:5:// @dart = 2.9
dwds/lib/src/debugging/dart_scope.dart:5:// @dart = 2.9
dwds/lib/src/debugging/debugger.dart:5:// @dart = 2.9
dwds/lib/src/debugging/execution_context.dart:5:// @dart = 2.9
dwds/lib/src/debugging/frame_computer.dart:5:// @dart = 2.9
dwds/lib/src/debugging/inspector.dart:5:// @dart = 2.9
dwds/lib/src/debugging/instance.dart:5:// @dart = 2.9
dwds/lib/src/debugging/libraries.dart:5:// @dart = 2.9
dwds/lib/src/debugging/location.dart:5:// @dart = 2.9
dwds/lib/src/debugging/metadata/class.dart:5:// @dart = 2.9
dwds/lib/src/debugging/metadata/function.dart:5:// @dart = 2.9
dwds/lib/src/debugging/metadata/module_metadata.dart:5:// @dart = 2.9
dwds/lib/src/debugging/metadata/provider.dart:5:// @dart = 2.9
dwds/lib/src/debugging/modules.dart:5:// @dart = 2.9
dwds/lib/src/debugging/remote_debugger.dart:5:// @dart = 2.9
dwds/lib/src/debugging/skip_list.dart:5:// @dart = 2.9
dwds/lib/src/debugging/webkit_debugger.dart:5:// @dart = 2.9
dwds/lib/src/dwds_vm_client.dart:5:// @dart = 2.9
dwds/lib/src/events.dart:5:// @dart = 2.9
dwds/lib/src/handlers/dev_handler.dart:5:// @dart = 2.9
dwds/lib/src/handlers/injector.dart:5:// @dart = 2.9
dwds/lib/src/handlers/socket_connections.dart:5:// @dart = 2.9
dwds/lib/src/loaders/build_runner_require.dart:5:// @dart = 2.9
dwds/lib/src/loaders/frontend_server_require.dart:5:// @dart = 2.9
dwds/lib/src/loaders/legacy.dart:5:// @dart = 2.9
dwds/lib/src/loaders/require.dart:5:// @dart = 2.9
dwds/lib/src/loaders/strategy.dart:5:// @dart = 2.9
dwds/lib/src/readers/asset_reader.dart:5:// @dart = 2.9
dwds/lib/src/readers/frontend_server_asset_reader.dart:5:// @dart = 2.9
dwds/lib/src/readers/proxy_server_asset_reader.dart:5:// @dart = 2.9
dwds/lib/src/servers/devtools.dart:5:// @dart = 2.9
dwds/lib/src/servers/extension_backend.dart:5:// @dart = 2.9
dwds/lib/src/servers/extension_debugger.dart:5:// @dart = 2.9
dwds/lib/src/services/app_debug_services.dart:5:// @dart = 2.9
dwds/lib/src/services/chrome_proxy_service.dart:5:// @dart = 2.9
dwds/lib/src/services/debug_service.dart:5:// @dart = 2.9
dwds/lib/src/services/expression_compiler.dart:5:// @dart = 2.9
dwds/lib/src/services/expression_compiler_service.dart:5:// @dart = 2.9
dwds/lib/src/services/expression_evaluator.dart:5:// @dart = 2.9
dwds/lib/src/sockets.dart:5:// @dart = 2.9
dwds/lib/src/utilities/batched_stream.dart:5:// @dart = 2.9
dwds/lib/src/utilities/conversions.dart:5:// @dart = 2.9
dwds/lib/src/utilities/dart_uri.dart:5:// @dart = 2.9
dwds/lib/src/utilities/ddc_names.dart:5:// @dart = 2.9
dwds/lib/src/utilities/domain.dart:5:// @dart = 2.9
dwds/lib/src/utilities/objects.dart:5:// @dart = 2.9
dwds/lib/src/utilities/shared.dart:5:// @dart = 2.9
dwds/test/build/ensure_version_test.dart:5:// @dart = 2.9
dwds/test/build/min_sdk_test.dart:5:// @dart = 2.9
dwds/test/build_daemon_breakpoint_test.dart:5:// @dart = 2.9
dwds/test/build_daemon_callstack_test.dart:5:// @dart = 2.9
dwds/test/build_daemon_evaluate_test.dart:5:// @dart = 2.9
dwds/test/chrome_proxy_service_test.dart:5:// @dart = 2.9
dwds/test/dart_uri_file_uri_test.dart:5:// @dart = 2.9
dwds/test/dart_uri_test.dart:5:// @dart = 2.9
dwds/test/debug_extension_test.dart:5:// @dart = 2.9
dwds/test/debug_service_test.dart:5:// @dart = 2.9
dwds/test/debugger_test.dart:5:// @dart = 2.9
dwds/test/devtools_test.dart:5:// @dart = 2.9
dwds/test/evaluate_common.dart:5:// @dart = 2.9
dwds/test/events_test.dart:5:// @dart = 2.9
dwds/test/expression_compiler_service_test.dart:5:// @dart = 2.9
dwds/test/extension_backend_test.dart:5:// @dart = 2.9
dwds/test/extension_debugger_test.dart:5:// @dart = 2.9
dwds/test/fixtures/context.dart:5:// @dart = 2.9
dwds/test/fixtures/debugger_data.dart:5:// @dart = 2.9
dwds/test/fixtures/fakes.dart:5:// @dart = 2.9
dwds/test/fixtures/logging.dart:5:// @dart = 2.9
dwds/test/fixtures/server.dart:5:// @dart = 2.9
dwds/test/fixtures/utilities.dart:5:// @dart = 2.9
dwds/test/frontend_server_breakpoint_test.dart:5:// @dart = 2.9
dwds/test/frontend_server_callstack_test.dart:5:// @dart = 2.9
dwds/test/frontend_server_evaluate_test.dart:5:// @dart = 2.9
dwds/test/handlers/asset_handler_test.dart:5:// @dart = 2.9
dwds/test/handlers/injector_test.dart:5:// @dart = 2.9
dwds/test/inspector_test.dart:5:// @dart = 2.9
dwds/test/instance_test.dart:5:// @dart = 2.9
dwds/test/listviews_test.dart:5:// @dart = 2.9
dwds/test/location_test.dart:5:// @dart = 2.9
dwds/test/metadata/class_test.dart:5:// @dart = 2.9
dwds/test/metadata_test.dart:5:// @dart = 2.9
dwds/test/objects_test.dart:5:// @dart = 2.9
dwds/test/readers/frontend_server_asset_reader_test.dart:5:// @dart = 2.9
dwds/test/readers/proxy_server_asset_reader_test.dart:5:// @dart = 2.9
dwds/test/refresh_test.dart:5:// @dart = 2.9
dwds/test/reload_test.dart:5:// @dart = 2.9
dwds/test/restore_breakpoints_test.dart:5:// @dart = 2.9
dwds/test/run_request_test.dart:5:// @dart = 2.9
dwds/test/screenshot_test.dart:5:// @dart = 2.9
dwds/test/sdk_configuration_test.dart:5:// @dart = 2.9
dwds/test/skip_list_test.dart:5:// @dart = 2.9
dwds/test/variable_scope_test.dart:5:// @dart = 2.9
dwds/test/web/batched_stream_test.dart:5:// @dart = 2.9
dwds/tool/copy_builder.dart:5:// @dart = 2.9
dwds/web/client.dart:5:// @dart = 2.9
dwds/web/promise.dart:5:// @dart = 2.9
dwds/web/reloader/legacy_restarter.dart:5:// @dart = 2.9
dwds/web/reloader/manager.dart:5:// @dart = 2.9
dwds/web/reloader/require_restarter.dart:5:// @dart = 2.9
dwds/web/reloader/restarter.dart:5:// @dart = 2.9
dwds/web/run_main.dart:1:// @dart = 2.9
```

See https://github.com/dart-lang/sdk/issues/49169 for more context.

**Comment by annagrin** [comment] 2022-07-15 00:22
Duplicate of https://github.com/dart-lang/webdev/issues/1327

**Closed** 2022-08-16 20:06 UTC
