### ISSUE TITLE
Webdev serving on localhost but not on 127.0.0.1 

### ISSUE THREAD

**Issue by Thiltal** [dart-lang/webdev#402] opened 2019-05-25 10:15 UTC
I'm runnning webdev 2.0.5 on windows 10. I can connect to localhost, but cannot connect to 127.0.0.1. It is important, because I'm using nodejs http-proxy-middleware connecting to 127.0.0.1 even if I write localhost.

127.0.0.1 is woking if I'm listening on node server.

This issue is probably similar as:
[https://github.com/dart-lang/webdev/issues/233](https://github.com/dart-lang/webdev/issues/233)

**Comment by Thiltal** [comment] 2019-05-25 12:10
I've found workaround `webdev serve --hostname 127.0.0.1 web:8083`

**Comment by grouma** [comment] 2019-05-28 19:55
We listen on the loopback by default unless the user explicitly passes a hostname:
https://github.com/dart-lang/webdev/blob/master/dwds/lib/service.dart#L85

My guess is that your machine is listening on IPv6 only (`::1`). I don't think there's much we can do in `webdev` in this case. I'm going to close this as working as intended.

**Closed by grouma** 2019-05-28 19:55 UTC
