### ISSUE TITLE
error while debugging on web

### ISSUE THREAD

**Issue by fardump** [dart-lang/webdev#1151] opened 2020-10-16 04:17 UTC
error while debugging on web, and the error is : 

NoSuchMethodError: method not found: 'get$digestsPath' (J.getInterceptor$x(...).get$digestsPath is not a function)
TypeError: J.getInterceptor$x(...).get$digestsPath is not a function
    at Object.get$digestsPath$x (http://localhost:53677/dwds/src/injected/client.js:3529:43)
    at http://localhost:53677/dwds/src/injected/client.js:22757:60
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:53677/dwds/src/injected/client.js:3824:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:53677/dwds/src/injected/client.js:11021:12)
    at Object._asyncStartSync (http://localhost:53677/dwds/src/injected/client.js:3788:20)
    at RequireRestarter._getDigests$0 (http://localhost:53677/dwds/src/injected/client.js:22769:16)
    at http://localhost:53677/dwds/src/injected/client.js:22784:48
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:53677/dwds/src/injected/client.js:3824:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:53677/dwds/src/injected/client.js:11021:12)
    at Object._asyncStartSync (http://localhost:53677/dwds/src/injected/client.js:3788:20)
    at RequireRestarter._initialize$0 (http://localhost:53677/dwds/src/injected/client.js:22792:16)
    at http://localhost:53677/dwds/src/injected/client.js:8594:45
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:53677/dwds/src/injected/client.js:3824:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:53677/dwds/src/injected/client.js:11021:12)
    at Object._asyncStartSync (http://localhost:53677/dwds/src/injected/client.js:3788:20)
    at Object.RequireRestarter_create (http://localhost:53677/dwds/src/injected/client.js:8606:16)
    at http://localhost:53677/dwds/src/injected/client.js:22344:38
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:53677/dwds/src/injected/client.js:3824:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:53677/dwds/src/injected/client.js:11021:12)
    at _awaitOnObject_closure.call$1 (http://localhost:53677/dwds/src/injected/client.js:11007:32)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:53677/dwds/src/injected/client.js:4152:18)
    at _CustomZone.runUnary$2$2 (http://localhost:53677/dwds/src/injected/client.js:12326:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:53677/dwds/src/injected/client.js:11387:51)
    at Object._Future__propagateToListeners (http://localhost:53677/dwds/src/injected/client.js:3936:93)
    at _Future._complete$1 (http://localhost:53677/dwds/src/injected/client.js:11211:11)
    at Object._cancelAndValue (http://localhost:53677/dwds/src/injected/client.js:4091:16)
    at Stream_first_closure0.call$1 (http://localhost:53677/dwds/src/injected/client.js:11479:9)
    at _EventStreamSubscription_onData_closure.call$1 (http://localhost:53677/dwds/src/injected/client.js:17334:30)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:53677/dwds/src/injected/client.js:4158:16)
    at _CustomZone.runUnary$2$2 (http://localhost:53677/dwds/src/injected/client.js:12326:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:53677/dwds/src/injected/client.js:12258:14)
    at _CustomZone_bindUnaryCallbackGuarded_closure.call$1 (http://localhost:53677/dwds/src/injected/client.js:12461:25)
    at invokeClosure (http://localhost:53677/dwds/src/injected/client.js:1205:26)
    at EventSource.<anonymous> (http://localhost:53677/dwds/src/injected/client.js:1224:18)

**Comment by grouma** [comment] 2020-10-16 16:36
Dupe of https://github.com/dart-lang/webdev/issues/1133

**Closed by grouma** 2020-10-16 16:36 UTC
