### ISSUE TITLE
HTTP error on a web page deployed to GitHub Pages

### ISSUE THREAD

**Issue by myConsciousness** [dart-lang/webdev#1558] opened 2022-04-05 04:49 UTC
Hi amazing developers!

I get the following error in the console when I deploy and access a web resource created with Flutter for Web on GitHub Pages.
The version of Flutter is `2.10.4`.

I'm using the `index.html` as it was created when the project was generated, are there any definitions that I should edit?

```bash
batch-dart.github.io/:1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://batch-dart.github.io/') with script ('https://batch-dart.github.io/flutter_service_worker.js?v=4115545560'): A bad HTTP response code (404) was received when fetching the script.
manifest.json:1          Failed to load resource: the server responded with a status of 404 ()
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
(index):91 Failed to load app from service worker. Falling back to plain <script> tag.
(anonymous) @ (index):91
main.dart.js:1          Failed to load resource: the server responded with a status of 404 ()
manifest.json:1          Failed to load resource: the server responded with a status of 404 ()
```

Thank you.

**Comment by natebosch** [comment] 2022-05-03 22:14
It looks like this is an issue being reported about flutter.

Issues can't be transferred across orgs, Please reopen at https://github.com/flutter/flutter/issues with more details and some reproduction steps.

**Closed by natebosch** 2022-05-03 22:14 UTC
