### ISSUE TITLE
--hot-restart: browser app crashes when adding import

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/webdev#122] opened 2019-02-07 23:32 UTC
Repro: get app running in chrome with `--hot-restart`.

Edit a file "in use" to add an import to another library – and you get a crash in Chrome

<img width="1723" alt="screen shot 2019-02-07 at 3 27 12 pm" src="https://user-images.githubusercontent.com/17034/52449830-847e5b80-2aed-11e9-86f0-975716da4852.png">

CC @jakemac53 

Using webdev @ https://github.com/dart-lang/webdev/commit/2a7fdcad4f2a330786024dadbda03635fbfd5740

**Comment by grouma** [comment] 2019-02-08 19:55
I'm thinking the logic here is wrong: https://github.com/dart-lang/webdev/blob/master/webdev/lib/src/serve/reload_client/hot_restart/client.dart#L35

Do we have to do a hard reload if the current module isn't loaded? I believe the `updateGraph` method won't have the necessary information which will result in undefined behavior in our compare function: https://github.com/dart-lang/webdev/blob/master/webdev/lib/src/serve/reload_client/hot_restart/reloading_manager.dart#L34

**Comment by grouma** [comment] 2019-04-22 21:46
I can't reproduce this on `2.0.0`. Closing for now. If you experience it again please reopen.

**Closed by grouma** 2019-04-22 21:46 UTC
