### ISSUE TITLE
Define option not reachable

### ISSUE THREAD

**Issue by sestegra** [dart-lang/webdev#73] opened 2018-07-31 13:40 UTC
On Dart 1.x, when compiling to JS, it was possible to add parameters at compilation time (for instance for version, backend configuration...).

```
$ pub build --define version=1337
```

Now, on Dart 2, with `webdev build`, no option is available to do so.

**Comment by jakemac53** [comment] 2018-07-31 15:46
The problem is these could have arbitrary effects on the build, and so we would have to invalidate the entire build any time you changed the defines.

You can instead use builder options to configure things differently for release/debug mode, or arbitrary --config values, but that is certainly more involved (basically, you would include a builder which takes some configuration that it writes out to a Dart file, and then you import that dart file).

**Comment by lejard-h** [comment] 2018-08-02 08:04
linked to https://github.com/dart-lang/build/issues/1053

**Comment by jakemac53** [comment] 2019-04-17 21:02
I am going to close this as not planned, as that is the current state.

Beyond even the issues around build invalidation there are other problems relating to these constants that cause a lot of problems for modular builds.

**Closed by jakemac53** 2019-04-17 21:02 UTC
Labels: wontfix
