### ISSUE TITLE
[dwds] launching flutter web in debug from vscode results in blank screen

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/webdev#904] opened 2020-02-20 17:23 UTC
If I do "Start Debugging" from VSCode in Flutter Gallery, Chrome opens, but the app doesn't render.

If I refresh the browser or run `window.$dartRunMain()`, the app then renders.

@grouma @jakemac53

**Comment by jakemac53** [comment] 2020-02-20 17:28
This is likely a flutter_tool issue where it is serving the app before the rest of the backend services are ready, but we can investigate and move there once we confirm.

**Comment by grouma** [comment] 2020-02-20 18:15
I'm unable to reproduce this on my Linux machine. Can you give more environment details? For example, SDK, OS etc.

**Comment by vsmenon** [comment] 2020-02-20 18:23
Let me make sure I can repro with a clean Dart.

**Comment by vsmenon** [comment] 2020-02-20 18:24
I was on a Mac with master.

**Comment by grouma** [comment] 2020-02-20 18:24
Can't reproduce on my Mac with master either :/

**Comment by vsmenon** [comment] 2020-02-20 20:21
Okay, I'm seeing with:

engine: commit [0ef67b5e74c6a43915b72fc7ec682deed762206c](https://github.com/flutter/engine/commit/0ef67b5e74c6a43915b72fc7ec682deed762206c)
flutter: commit [52ee8a6c6565cd421dfa32042941eb40691f4746](https://github.com/flutter/flutter/commit/52ee8a6c6565cd421dfa32042941eb40691f4746)

along with the modification to make flutter use the local engine:
```
diff --git a/bin/flutter b/bin/flutter
index e0c18e2358..1baadbcf21 100755
--- a/bin/flutter
+++ b/bin/flutter
@@ -189,4 +189,4 @@ fi
 
 # FLUTTER_TOOL_ARGS isn't quoted below, because it is meant to be considered as
 # separate space-separated args.
-"$DART" --packages="$FLUTTER_TOOLS_DIR/.packages" $FLUTTER_TOOL_ARGS "$SNAPSHOT_PATH" "$@"
+"$DART" --packages="$FLUTTER_TOOLS_DIR/.packages" $FLUTTER_TOOL_ARGS "$SNAPSHOT_PATH" "--local-engine=host_debug_unopt" "$@"
```

**Comment by vsmenon** [comment] 2020-02-21 16:29
Seeing the same today with flutter tip-of-tree and no local engine.  Flutter at:

```
commit 3275adb7fbd0758afbc00a978c3460e244cf864e (HEAD -> master, origin/master, origin/HEAD)
Author: Clement Skau <cskau-g@users.noreply.github.com>
Date:   Fri Feb 21 13:38:56 2020 +0100

    Updates test expectations for stack traces. (#51185)
    ...
```

**Comment by vsmenon** [comment] 2020-02-21 16:30
This is all I see in Chrome console:
```
:55000/favicon.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to parse SourceMap: http://localhost:55000/dart_sdk.js.map
DevTools failed to parse SourceMap: http://localhost:55000/dwds/src/injected/client.dart.js.map
```

**Comment by DanTup** [comment] 2020-03-10 12:07
I'm seeing integration test failures in Dart-Code that I wonder if may be the same issue described here. I've traced it back to getting no response at all to `addreakpointWithScriptUri`:

```
[12:03:06 PM] [Observatory] [Info] [Dart & Flutter] ==> {"id":"9","method":"addBreakpointWithScriptUri","params":{"isolateId":"1","scriptUri":"file:///Users/danny/Dev/Dart-Code/src/test/test_projects/flutter_hello_world/lib/main.dart","line":48}}
```

The debug adapter sits around waiting for a response, but nothing ever comes (neither success not failure). This results in VS Code just sitting their waiting (and never resuming the application from it's start-paused state).

The only things in the spawned Chrome windows dev tools are the things @vsmenon posted above.

**Comment by DanTup** [comment] 2020-03-10 12:08
(FWIW, this would only occur if you have breakpoints, which might be why some see it and some don't, since we won't call this if there aren't any).

**Comment by grouma** [comment] 2020-03-19 19:49
I'm hoping this is resolved by https://github.com/dart-lang/webdev/pull/919. @vsmenon can you verify that you can no longer reproduce this at master?

**Comment by DanTup** [comment] 2020-04-14 17:25
Assuming that change would've made Flutter master (I think it was updated fairly recently with latest changes?), I unskipped one of my tests and ran it, and it no longer freezes without responding, but I do get an unexpected error ("Bad state: Future already completed"):

```

[6:20:37 PM] [Observatory] [Info] [Dart & Flutter] ==> {"id":"24","method":"addBreakpointWithScriptUri","params":{"isolateId":"760","scriptUri":"file:///Users/danny/Dev/Dart-Code/src/test/test_projects/flutter_hello_world/lib/main.dart","line":0}}
[6:20:37 PM] [Observatory] [Info] [Dart & Flutter] ==> {"id":"25","method":"addBreakpointWithScriptUri","params":{"isolateId":"760","scriptUri":"file:///Users/danny/Dev/Dart-Code/src/test/test_projects/flutter_hello_world/lib/main.dart","line":48}}
[6:20:37 PM] [Observatory] [Info] [Dart & Flutter] <== {"jsonrpc":"2.0","id":"24","error":{"code":102,"data":null,"message":"The VM is unable to add a breakpoint at the specified line or function"}}
[6:20:37 PM] [Observatory] [Info] [Dart & Flutter] <== {"jsonrpc":"2.0","id":"25","error":{"code":-32603,"message":"Bad state: Future already completed\n#0      _AsyncCompleter.complete (dart:async/future_impl.dart:42:31)\n#1      Modules._initializeMapping (package:dwds/src/debugging/modules.dart:116:22)\n<asynchronous suspension>\n#2      Modules.moduleForSource (package:dwds/src/debugging/modules.dart:58:11)\n#3      Locations.locationsForDart (package:dwds/src/debugging/location.dart:142:33)\n#4      Locations.locationForDart (package:dwds/src/debugging/location.dart:172:14)\n#5      _Breakpoints.add.<anonymous closure> (package:dwds/src/debugging/debugger.dart:612:38)\n<asynchronous suspension>\n#6      _Breakpoints.add.<anonymous closure> (package:dwds/src/debugging/debugger.dart)\n#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)\n#8      _Breakpoints.add (package:dwds/src/debugging/debugger.dart:609:32)\n#9      Debugger.addBreakpoint (package:dwds/src/debugging/debugger.dart:260:25)\n#10     ChromeProxyService.addBreakpointWithScriptUri (package:dwds/src/services/chrome_proxy_service.dart:278:10)\n<asynchronous suspension>\n#11     VmServerConnection._delegateRequest (package:vm_service/src/vm_service.dart:1180:51)\n#12     _rootRunUnary (dart:async/zone.dart:1192:38)\n#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)\n#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)\n#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)\n#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)\n#17     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)\n#18     _MapStream._handleData (dart:async/stream_pipe.dart:234:10)\n#19     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)\n#20     _rootRunUnary (dart:async/zone.dart:1192:38)\n#21     _CustomZone.runUnary (dart:async/zone.dart:1085:19)\n#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)\n#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)\n#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)\n#25     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)\n#26     _StreamController._add (dart:async/stream_controller.dart:655:7)\n#27     _StreamController.add (dart:async/stream_controller.dart:597:5)\n#28     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)\n#29     _rootRunUnary (dart:async/zone.dart:1192:38)\n#30     _CustomZone.runUnary (dart:async/zone.dart:1085:19)\n#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)\n#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)\n#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)\n#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)\n#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)\n#36     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)\n#37     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)\n#38     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)\n#39     _rootRunUnary (dart:async/zone.dart:1192:38)\n#40     _CustomZone.runUnary (dart:async/zone.dart:1085:19)\n#41     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)\n#42     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)\n#43     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)\n#44     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)\n#45     _StreamController._add (dart:async/stream_controller.dart:655:7)\n#46     _StreamController.add (dart:async/stream_controller.dart:597:5)\n#47     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)\n#48     _rootRunUnary (dart:async/zone.dart:1196:13)\n#49     _CustomZone.runUnary (dart:async/zone.dart:1085:19)\n#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)\n#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)\n#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)\n#53     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)\n#54     _StreamController._add (dart:async/stream_controller.dart:655:7)\n#55     _StreamController.add (dart:async/stream_controller.dart:597:5)\n#56     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)\n#57     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)\n#58     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)\n#59     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)\n#60     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)\n#61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)\n"}}
```

The first error is expected (we send a breakpoint for an invalid location), but the second one we expect to correctly set a breakpoint.

[flutter_run_debugger_launch_on_chrome_stops_at_a_breakpoint_after_each_reload_1_.txt](https://github.com/dart-lang/webdev/files/4476749/flutter_run_debugger_launch_on_chrome_stops_at_a_breakpoint_after_each_reload_1_.txt)

**Comment by jakemac53** [comment] 2020-04-14 19:23
Looks like a race condition in this method https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/debugging/modules.dart#L86. If it gets called again before the first call completes then the completer won't be completed yet, should be an easy fix.

**Comment by grouma** [comment] 2020-04-14 19:26
Yup. I have a pending PR.

**Closed** 2020-04-15 19:27 UTC

**Comment by DanTup** [comment] 2020-05-05 16:50
Thanks, this seems to have fixed my integration tests :-)
