### ISSUE TITLE
Unhandled error right after web debug build

### ISSUE THREAD

**Issue by Jancikos** [dart-lang/webdev#1148] opened 2020-10-14 08:37 UTC
It showed after update to this Flutter version:
            Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [Version 10.0.18363.1082], locale sk-SK)

Error trace: 

NoSuchMethodError: method not found: 'get$digestsPath' (J.getInterceptor$x(...).get$digestsPath is not a function)
TypeError: J.getInterceptor$x(...).get$digestsPath is not a function
    at Object.get$digestsPath$x (http://localhost:63463/dwds/src/injected/client.js:3446:43)
    at http://localhost:63463/dwds/src/injected/client.js:22764:60
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:63463/dwds/src/injected/client.js:3744:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:63463/dwds/src/injected/client.js:10956:12)
    at Object._asyncStartSync (http://localhost:63463/dwds/src/injected/client.js:3708:20)
    at RequireRestarter._getDigests$0 (http://localhost:63463/dwds/src/injected/client.js:22776:16)
    at http://localhost:63463/dwds/src/injected/client.js:22791:48
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:63463/dwds/src/injected/client.js:3744:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:63463/dwds/src/injected/client.js:10956:12)
    at Object._asyncStartSync (http://localhost:63463/dwds/src/injected/client.js:3708:20)
    at RequireRestarter._initialize$0 (http://localhost:63463/dwds/src/injected/client.js:22799:16)
    at http://localhost:63463/dwds/src/injected/client.js:8566:45
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:63463/dwds/src/injected/client.js:3744:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:63463/dwds/src/injected/client.js:10956:12)
    at Object._asyncStartSync (http://localhost:63463/dwds/src/injected/client.js:3708:20)
    at Object.RequireRestarter_create (http://localhost:63463/dwds/src/injected/client.js:8578:16)
    at http://localhost:63463/dwds/src/injected/client.js:22359:38
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:63463/dwds/src/injected/client.js:3744:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:63463/dwds/src/injected/client.js:10956:12)
    at _awaitOnObject_closure.call$1 (http://localhost:63463/dwds/src/injected/client.js:10942:32)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:63463/dwds/src/injected/client.js:4062:18)
    at _CustomZone.runUnary$2$2 (http://localhost:63463/dwds/src/injected/client.js:12275:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:63463/dwds/src/injected/client.js:11329:61)
    at Object._Future__propagateToListeners (http://localhost:63463/dwds/src/injected/client.js:3855:104)
    at _Future._complete$1 (http://localhost:63463/dwds/src/injected/client.js:11145:11)
    at Object._cancelAndValue (http://localhost:63463/dwds/src/injected/client.js:3992:16)
    at Stream_first_closure.call$1 (http://localhost:63463/dwds/src/injected/client.js:11408:9)
    at _EventStreamSubscription_closure.call$1 (http://localhost:63463/dwds/src/injected/client.js:17369:26)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:63463/dwds/src/injected/client.js:4066:16)
    at _CustomZone.runUnary$2$2 (http://localhost:63463/dwds/src/injected/client.js:12275:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:63463/dwds/src/injected/client.js:12203:14)
    at _CustomZone_bindUnaryCallbackGuarded_closure.call$1 (http://localhost:63463/dwds/src/injected/client.js:12439:25)
    at invokeClosure (http://localhost:63463/dwds/src/injected/client.js:1172:26)
    at EventSource.<anonymous> (http://localhost:63463/dwds/src/injected/client.js:1191:18)

**Comment by grouma** [comment] 2020-10-14 16:58
Dupe of https://github.com/dart-lang/webdev/issues/1133

**Closed by grouma** 2020-10-14 16:58 UTC
