### ISSUE TITLE
Unverified breakpoints in specific file using VSCode debug

### ISSUE THREAD

**Issue by NicolasDionB** [dart-lang/webdev#874] opened 2020-01-22 13:27 UTC
I have a Flutter project and have been debuging it for a while now using VSCode. I just found recently that, in a specific file, all my breakpoints are marked "Unverified" when I start debugging my project from VSCode.

I originaly opened an issue on Dart-Code (https://github.com/Dart-Code/Dart-Code/issues/2221) but we tought it could be related to webdev.

My file is imported same as all the others, nothing special. I have a core class which instantiates my managers, like so:

```dart
import 'package:bloc/bloc.dart';
import 'package:meta/meta.dart';

import 'package:live_app/managers/chat/chat_manager.dart';
import 'package:live_app/managers/user/user_manager.dart';

class BaseCore extends Bloc<CoreBaseEvent, CoreBaseState> {
  UserManager _userManager;
  IUserManager get userManager => _userManager;

  ChatManager _chatManager;
  IChatManager get chatManager => _chatManager;

  BaseCore() {
    _userManager = UserManager(_hubConnection);
    _chatManager = ChatManager(_hubConnection, EHubPacketType.VROOMCHAT, _userManager);
  }

  // ...
```

I can place a breakpoint in my `UserManager` and it works, while placing one in my `ChatManager` doesn't. Any idea?

I'm using VSCode 1.41.1 on Windows 10, with Dart-Code extension 3.7.1.

**Comment by jakemac53** [comment] 2020-01-22 14:29
Just to confirm, this is for flutter web?

**Comment by NicolasDionB** [comment] 2020-01-22 14:32
@jakemac53 Yup, this is for Flutter web.

**Comment by jakemac53** [comment] 2020-01-22 14:42
cc @grouma who is most familiar with the breakpoint mapping logic. My guess is that we are failing to map the dart breakpoint position to a javascript position for some reason.

It might be difficult to diagnose this without a reproduction case that we can run though.

**Comment by NicolasDionB** [comment] 2020-01-22 16:04
I'm trimming the code down. Can I send it by email to someone?

**Comment by jakemac53** [comment] 2020-01-22 17:27
Unfortunately i don't think we can accept any non-public code as a general policy (or open zip files at all for that matter)

**Comment by NicolasDionB** [comment] 2020-01-22 17:57
Well that's too bad then. I have code to repro but don't have the time to take it all the way down to minimal example, sorry. I already took time to trim it. Hope you can still find something.

**Comment by jakemac53** [comment] 2020-01-22 18:01
We might be able to provide a branch or something of webdev that you could use which would just add some logging that might be useful?

We do want to understand the corner cases here.

**Comment by NicolasDionB** [comment] 2020-01-22 18:16
Sure. Just head me to intructions to commit my small project.

**Comment by grouma** [comment] 2020-01-22 18:27
Does this work in Dart DevTools, outside of VS Code?

The source map logic is here:
https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/debugging/location.dart#L106

You can do some basic debugging to see if the provided source file has associated token positions.

**Comment by NicolasDionB** [comment] 2020-01-24 13:27
@grouma Sorry I have no idea how to debug that. Also I'm trying to place a breakpoint on a variable set or within a function. I know I can't place breakpoints anywhere. I do this in other files and it works, it just doesn't on some files for some reason...

**Comment by DanTup** [comment] 2020-01-24 16:36
I did some testing and found that files that are not loaded give a different error:

```
Invalid argument (uri): Unknown library: "file:///C:/Users/danny/Desktop/live_app/lib/managers/vroom/vroom_manager.dart"
#0      new DartUri._fromFileUri (package:dwds/src/utilities/dart_uri.dart:142:5)
#1      new DartUri (package:dwds/src/utilities/dart_uri.dart:112:49)
#2      ChromeProxyService.addBreakpointWithScriptUri (package:dwds/src/services/chrome_proxy_service.dart:253:19)
```

But for the file in question here, the error is:

```
<== {"jsonrpc":"2.0","error":{"code":102,"data":null,"message":"The VM is unable to add a breakpoint at the specified line or function"},"id":"1150"}
```

I tried sending it for a huge number of lines in the file, but they all give the same response. It seems like the proxy knows this is a valid file, but can't map *any* locations in it.

I can't see anything obviously different that file - it's UTF8 CRLF like the others, and seems to be imported in the same way.

In DevTools, the file shows up in the Libraries list (and shows the correct contents), but any attempt to add a breakpoint on any line just silently does nothing (the same as trying to add to an invalid line in another file).

@grouma where is the mapping to translate positions? If I was to make this use dwds from source, where would be a good place to add some logging to see why it's not mapping this?

**Comment by grouma** [comment] 2020-01-24 17:57
For a given file there is a corresponding token position table. This table contains all the valid potential breakpoints. It is computed here:
https://github.com/dart-lang/webdev/blob/d6898d15e0a6ff7acadb009bbd5260afa761665b/dwds/lib/src/debugging/location.dart#L185

**Comment by DanTup** [comment] 2020-01-27 17:53
That function wasn't called, but after much debugging I ended up with some logging here:

![Untitled](https://user-images.githubusercontent.com/1078012/73199915-b0935200-412d-11ea-82b1-89e66e8ea699.png)

And amongst the output when I ran it, I found this:

```
MISMATCHED PATH:
  packages/live_app/managers/chat/bloc/../chat_manager.dart
  packages/live_app/managers/chat/chat_manager.dart
```

So somehow `location.dartLocation.uri.serverPath` is ending up with `foo/../` in it that appears to be unexpected. I'm not entirely sure where this comes from (or the correct place to resolve it), but hopefully this will help repro!

**Comment by DanTup** [comment] 2020-01-27 17:58
Looks like this might fix it (in `dwds/lib/src/debugging/location.dart`), though I don't know if it's the correct place for it.

![fix](https://user-images.githubusercontent.com/1078012/73200353-85f5c900-412e-11ea-9694-6c3947940a82.png)

**Comment by jakemac53** [comment] 2020-01-27 18:07
Nice catch! It definitely looks like we just need to normalize the path.

**Comment by grouma** [comment] 2020-01-27 23:57
@DanTup awesome work. Feel free to make a PR and I'll merge the change :D

**Comment by awhitford** [comment] 2020-06-07 18:28
I am experiencing this **Unverified Breakpoint** problem.  Did it resurface?

**Comment by grouma** [comment] 2020-06-08 17:22
Can you provide a minimal repo that I can use for debugging?

**Comment by awhitford** [comment] 2020-06-08 17:27
Please note that when I restarted VS Code, it gave me a message that I had breakpoints in another project and asked if I wanted to enable that -- there is a VS Code setting somewhere.  Luckily, I just have to click a button on that prompt and it looks like the setting is updated.

I'm unclear as to what setting was changed.  It might be this:
```"debug.allowBreakpointsEverywhere": true```
but I'm not 100% sure.  I think I tried changing that first, but it didn't work.

**Comment by grouma** [comment] 2020-06-08 17:30
cc @DanTup

**Comment by DanTup** [comment] 2020-06-08 17:33
> when I restarted VS Code, it gave me a message that I had breakpoints in another project and asked if I wanted to enable that -- there is a VS Code setting somewhere

That prompt sets the `dart.debugSdkLibraries` and `dart.debugExternalLibraries` settings, and I don't think it actually changes any behaviour for web right now (it's related to https://github.com/dart-lang/webdev/issues/606). The prompt is actually bug in the current version, it'll pop up even if you already have those settings enabled (which is incorrect).

I wouldn't expect it to change whether VS code shows breakpoints as resolved or not. Currently the VS Code extension should always mark breakpoints as resolved (as breakpoint resolution is not handled correctly yet) unless the VM service rejects the breakpoint (as it did above, due to the path mismatch).

If you can still repro this, running the **Dart: Capture Logs** command and ticking only the **Debugger** option and will capture the traffic between VS Code and the VM service which might give some indication of why it failed.

**Comment by jvieirar** [comment] 2020-07-02 07:55
Just one note on this, I got same error but solved it with relative paths on the imports instead of local package imports.
```
import 'package:live_app/managers/chat/chat_manager.dart';
import 'package:live_app/managers/user/user_manager.dart';
```
You could try with
```
import './managers/chat/chat_manager.dart';
import './managers/user/user_manager.dart';
```
It solved for me :)

**Comment by awhitford** [comment] 2020-07-02 15:42
@DanTup I just wanted to update this thread and confirm that the problem seems to have disappeared after clicking on the prompt about supporting breakpoints outside my project.  I am also witnessing that this prompt keeps coming up across restarts.  However, my main concern was that I wasn't able to breakpoint on a dependency, and now I can, so that's good.

**Comment by DanTup** [comment] 2020-07-02 15:45
>  I am also witnessing that this prompt keeps coming up across restarts.

Are you on the latest version of Dart-Code (1.12)? If so, this prompt should only appear if a) you have breakpoints in files outside your project *and* your debug settings are set to "Just my code". If you change the settings to also debug SDK/packages, the prompt should not appear the next time. If you see it coming back, please file an issue (I tested, but couldn't repro - it didn't appear once I had picked "Debug my code.+ packages + SDK").

**Comment by NicolasDionB** [comment] 2020-07-06 18:01
> Just one note on this, I got same error but solved it with relative paths on the imports instead of local package imports.
> ...
> > You could try with
> > ```
> import './managers/chat/chat_manager.dart';
> import './managers/user/user_manager.dart';
> ```
> 
> It solved for me :)

If it does work, it's a bit counter intuitive as VSCode auto imports the longer version prefixed with `package:` so I would have to manually edit all imports I make... sorry but no!! But if that's true, surely there must be a solvable issue there... anyone?

**Comment by NicolasDionB** [comment] 2020-07-06 18:10
Well after doing a quick test with the latest version, it all seems to work now. Magic done as it seems! Thanks all!

**Comment by Dalimar95** [comment] 2022-01-11 13:20
Hi Guys I'm facing exactly the same issue was there regression in recent releases?

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)`

**Comment by DanTup** [comment] 2022-01-11 14:27
@Dalimar95 are you able to share a small repro project that triggers the issue?

**Comment by elliette** [comment] 2022-07-18 17:41
Closing this bug as not reproducible. Please re-open with a small repro example if this is still affecting you. Thank you!

**Closed by elliette** 2022-07-18 17:41 UTC

**Comment by lukaszciastko** [comment] 2023-11-02 10:16
I am also facing the very same issue with latest Flutter and can't debug the web app, which is a real problem for me. In the logs, I can see the compiler complaining about an unknown library (built_collection) for a dev dependency, which is a bit strange.

**Comment by DanTup** [comment] 2023-11-02 10:25
@lukaszciastko please file a new issue with instructions to reproduce and specific details about the behaviour you're seeing/what's not working. Thanks!
