### ISSUE TITLE
Can't load Kernel binary: File size is too small to a valid kernel file.

### ISSUE THREAD

**Issue by cooler-king** [dart-lang/webdev#70] opened 2018-07-26 20:02 UTC
This is happening to me after upgrading the Dart SDK from 69.0 to 69.3.  
Windows 10 x64:

```C:\dev\dart\dart-sdk\bin\dart.exe --enable-asserts --enable-vm-service:50107 C:\dev\github-vcd\frontend-dart\tools\detect_serve.dart --port 7777 --config dev/config/vcd_demo
Observatory listening on http://127.0.0.1:50107/

Package webdev is currently active at version 0.2.3+1.


Resolving dependencies...


+ args 1.4.4

+ charcode 1.1.2
+ collection 1.14.11
+ io 0.3.3
+ meta 1.1.6
+ path 1.6.2
+ pub_semver 1.4.2
+ source_span 1.4.1

+ stack_trace 1.9.3
+ string_scanner 1.0.3
+ webdev 0.2.3+1

+ yaml 2.1.15

Downloading webdev 0.2.3+1...


Precompiling executables...


Precompiled webdev:bin\webdev.


Installed executable webdev.


Activated webdev 0.2.3+1.


Can't load Kernel binary: File size is too small to a valid kernel file.

webdev failed with an unexpected exception.

Unable to spawn isolate: Error while initializing Kernel isolate
```

**Comment by alescdb** [comment] 2018-07-27 15:10
Hi,

I don't know if this will help (or even if it is related) but I had a similar issue. 
Deleting the .dart_tool directory resolved it for me.

**Comment by cooler-king** [comment] 2018-07-27 15:40
Thanks but that did not work for me.

69.0 and 69.2 work for me.
69.3 and 69.4 crash as above whether` .dart_tools` is deleted or not.

**Comment by alfinbi** [comment] 2018-07-27 20:34
it is also happening with me. I am using windows 10 and dart-sdk dev.69.4.

**Comment by Marco87Developer** [comment] 2018-07-29 16:06
I did a test with Dart SDK `2.0.0-dev.68.0`, but I received the same error message, even deleting `.dart_tools` folder.

**Comment by charlenopires** [comment] 2018-07-29 23:59
I received the same error message: 
_Can't load Kernel binary: File size is too small to a valid kernel file.
webdev failed with an unexpected exception.
Unable to spawn isolate: Error while initializing Kernel isolate_

I'm using Dart VM version: 2.0.0-dev.69.4 (Fri Jul 27 11:42:55 2018 +0200) on "windows_x64"

**Comment by MrWeatherallScience** [comment] 2018-07-31 15:48
I reverted back to 69.0 and the problem is resolved. Thanks for the advice.

**Comment by virgiltu** [comment] 2018-08-05 03:46
Same here in .5  what command can i use to request an older version of dart?

**Comment by moczix** [comment] 2018-08-05 18:43
@virgiltu go here https://www.dartlang.org/tools/sdk/archive
download the version you want, and replace your current dart-sdk with this downloaded one :D

**Comment by kevmoo** [comment] 2018-08-09 22:45
Please comment if this issue is not resolved by installing the latest SDK

**Closed by kevmoo** 2018-08-09 22:45 UTC

**Comment by gorychama** [comment] 2022-02-07 00:00
I have encountered the same error, and I downgraded flutter to solve it.
clean your project and run the command 
`flutter downgrade`

**Comment by kevmoo** [comment] 2022-02-07 04:53
From which version to which version?
