### ISSUE TITLE
Unhandled error detected in the injected client.js script.

### ISSUE THREAD

**Issue by lucasdidur** [dart-lang/webdev#1149] opened 2020-10-14 20:44 UTC
I got this error when load the site.

Webdev version: 2.5.3

```
NoSuchMethodError: method not found: 'get$appDigests' (J.getInterceptor$x(...).get$appDigests is not a function)
TypeError: J.getInterceptor$x(...).get$appDigests is not a function
    at Object.get$appDigests$x (http://127.0.0.1:8080/dwds/src/injected/client.js:2682:43)
    at http://127.0.0.1:8080/dwds/src/injected/client.js:23877:60
    at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:8080/dwds/src/injected/client.js:3003:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:10736:12)
    at Object._asyncStartSync (http://127.0.0.1:8080/dwds/src/injected/client.js:2968:20)
    at RequireRestarter._getDigests$0 (http://127.0.0.1:8080/dwds/src/injected/client.js:23889:16)
    at http://127.0.0.1:8080/dwds/src/injected/client.js:23904:48
    at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:8080/dwds/src/injected/client.js:3003:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:10736:12)
    at Object._asyncStartSync (http://127.0.0.1:8080/dwds/src/injected/client.js:2968:20)
    at RequireRestarter._initialize$0 (http://127.0.0.1:8080/dwds/src/injected/client.js:23912:16)
    at http://127.0.0.1:8080/dwds/src/injected/client.js:8098:45
    at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:8080/dwds/src/injected/client.js:3003:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:10736:12)
    at Object._asyncStartSync (http://127.0.0.1:8080/dwds/src/injected/client.js:2968:20)
    at Object.RequireRestarter_create (http://127.0.0.1:8080/dwds/src/injected/client.js:8110:16)
    at http://127.0.0.1:8080/dwds/src/injected/client.js:23431:38
    at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:8080/dwds/src/injected/client.js:3003:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:10736:12)
    at _awaitOnObject_closure.call$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:10722:32)
    at StaticClosure._rootRunUnary [as call$2$5] (http://127.0.0.1:8080/dwds/src/injected/client.js:3293:18)
    at _CustomZone.runUnary$2$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:12088:182)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://127.0.0.1:8080/dwds/src/injected/client.js:11114:61)
    at Object._Future__propagateToListeners (http://127.0.0.1:8080/dwds/src/injected/client.js:3114:104)
    at _Future._complete$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:10935:11)
    at Object._cancelAndValue (http://127.0.0.1:8080/dwds/src/injected/client.js:3251:16)
    at Stream_first_closure.call$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:11193:9)
    at _EventStreamSubscription_closure.call$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:18047:26)
    at StaticClosure._rootRunUnary [as call$2$5] (http://127.0.0.1:8080/dwds/src/injected/client.js:3297:16)
    at _CustomZone.runUnary$2$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:12088:182)
    at _CustomZone.runUnaryGuarded$1$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:12016:14)
    at _CustomZone_bindUnaryCallbackGuarded_closure.call$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:12261:25)
    at invokeClosure (http://127.0.0.1:8080/dwds/src/injected/client.js:1188:26)
    at EventSource.<anonymous> (http://127.0.0.1:8080/dwds/src/injected/client.js:1207:18)
```

**Comment by grouma** [comment] 2020-10-14 20:50
Dupe of https://github.com/dart-lang/webdev/issues/1133

**Closed by grouma** 2020-10-14 20:50 UTC
