### ISSUE TITLE
webdev serve unknown client error

### ISSUE THREAD

**Issue by CEbbinghaus** [dart-lang/webdev#1198] opened 2020-11-24 11:18 UTC
I opened an old project of mine up again and decided to see if I can get it running again. I ran `pub get` to install the dependencies and after running webdev serve I was greeted with this in the chrome console.

```
NoSuchMethodError: method not found: 'get$digestsPath' (J.getInterceptor$x(...).get$digestsPath is not a function)
TypeError: J.getInterceptor$x(...).get$digestsPath is not a function
    at Object.get$digestsPath$x (http://127.0.0.1:8080/dwds/src/injected/client.js:3536:43)
    at http://127.0.0.1:8080/dwds/src/injected/client.js:22757:60
    at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:8080/dwds/src/injected/client.js:3834:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:11028:12)
    at Object._asyncStartSync (http://127.0.0.1:8080/dwds/src/injected/client.js:3798:20)
    at RequireRestarter._getDigests$0 (http://127.0.0.1:8080/dwds/src/injected/client.js:22769:16)
    at http://127.0.0.1:8080/dwds/src/injected/client.js:22784:48
    at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:8080/dwds/src/injected/client.js:3834:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:11028:12)
    at Object._asyncStartSync (http://127.0.0.1:8080/dwds/src/injected/client.js:3798:20)
    at RequireRestarter._initialize$0 (http://127.0.0.1:8080/dwds/src/injected/client.js:22792:16)
    at http://127.0.0.1:8080/dwds/src/injected/client.js:8601:45
    at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:8080/dwds/src/injected/client.js:3834:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:11028:12)
    at Object._asyncStartSync (http://127.0.0.1:8080/dwds/src/injected/client.js:3798:20)
    at Object.RequireRestarter_create (http://127.0.0.1:8080/dwds/src/injected/client.js:8613:16)
    at http://127.0.0.1:8080/dwds/src/injected/client.js:22347:38
    at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:8080/dwds/src/injected/client.js:3834:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:11028:12)
    at _awaitOnObject_closure.call$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:11014:32)
    at StaticClosure._rootRunUnary [as call$2$5] (http://127.0.0.1:8080/dwds/src/injected/client.js:4162:18)
    at _CustomZone.runUnary$2$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:12334:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://127.0.0.1:8080/dwds/src/injected/client.js:11395:51)
    at Object._Future__propagateToListeners (http://127.0.0.1:8080/dwds/src/injected/client.js:3946:93)
    at _Future._complete$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:11218:11)
    at Object._cancelAndValue (http://127.0.0.1:8080/dwds/src/injected/client.js:4101:16)
    at Stream_first_closure0.call$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:11487:9)
    at _EventStreamSubscription_onData_closure.call$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:17346:30)
    at StaticClosure._rootRunUnary [as call$2$5] (http://127.0.0.1:8080/dwds/src/injected/client.js:4168:16)
    at _CustomZone.runUnary$2$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:12334:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:12266:14)
    at _CustomZone_bindUnaryCallbackGuarded_closure.call$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:12469:25)
    at invokeClosure (http://127.0.0.1:8080/dwds/src/injected/client.js:1205:26)
    at EventSource.<anonymous> (http://127.0.0.1:8080/dwds/src/injected/client.js:1224:18)
```

I deleted the build cache and the installed dart packages and tried reinstalling everything and rerunning it just to be greeted with the same result. 

I also ran it with the `--no-injected-client` argument and got this: 
![image](https://user-images.githubusercontent.com/31423391/100087492-eebee680-2ea2-11eb-8af7-b442f086d2e8.png)

**Comment by grouma** [comment] 2020-11-24 17:44
This is a dupe of https://github.com/dart-lang/webdev/issues/1133. I believe you just need to upgrade your SDK.

**Closed by grouma** 2020-11-24 17:44 UTC
