### ISSUE TITLE
Hot restart prints an error in the web console in devtools window

### ISSUE THREAD

**Issue by nshahan** [dart-lang/webdev#292] opened 2019-04-17 16:45 UTC
webdev v2.0.0-alpha.4
Spinning square example

Every time I trigger a hot restart I get an error printed to the web console in the devtools window:

```
Uncaught Instance of 'LibraryNotFound'
    at Object.wrapException (http://localhost:50715/main.dart.js:1116:17)
    at _rootHandleUncaughtError_closure.call$0 (http://localhost:50715/main.dart.js:19437:17)
    at Object._microtaskLoop (http://localhost:50715/main.dart.js:3750:21)
    at StaticClosure._startMicrotaskLoop (http://localhost:50715/main.dart.js:3756:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:50715/main.dart.js:17259:9)
    at invokeClosure (http://localhost:50715/main.dart.js:1306:26)
    at MutationObserver.<anonymous> (http://localhost:50715/main.dart.js:1326:18)
```

**Comment by jakemac53** [comment] 2019-04-17 17:46
Duplicate of https://github.com/flutter/devtools/issues/554 (I think  this is a devtools issue)

**Closed by jakemac53** 2019-04-17 17:46 UTC
