### ISSUE TITLE
Race conditions on simultaneous hot restarts

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1869] opened 2023-01-06 19:57 UTC
Repro:

- Update dwds dependency in flutter tools to point dwds master
- run `flutter run -d c --web-renderer html --verbose`

Then press 'r' a few times (fast). Observe warnings that expression evaluation failed while trying to pre-warm the compiler cache .

This particular failure is benign but indicates that we have a race condition between two `createIsolate` methods which could put the vm service into a bad state. It could be the cause of https://github.com/flutter/flutter/issues/117676.

**Comment by bkonyi** [comment] 2024-10-02 17:58
Assigning to @jyameo to verify this is still an issue.

**Comment by jyameo** [comment] 2024-10-24 17:25
I was not able to reproduce this issue. Closing the issue has it appear to have been fixed.

**Closed by jyameo** 2024-10-24 17:25 UTC
Labels: package:dwds, P2, triaged
