### ISSUE TITLE
webdev build results in "Crash when formatting: [AsciiControlCharacter]"

### ISSUE THREAD

**Issue by chalin** [dart-lang/webdev#63] opened 2018-06-21 19:15 UTC
## Environment

Dart VM version: 2.0.0-dev.64.1 (Thu Jun 21 08:47:55 2018 +0200) on "macos_x64"

## Steps to reproduce

1. Clone https://github.com/dart-lang/site-webdev
2. `cd examples/acx/lottery/1-base`
3. `pub upgrade`
4. `pub run build_runner build --delete-conflicting-outputs --output build`, and it builds fine
5. `webdev build`

## Expected result

The `webdev` build should succeed as well. Instead we get:

```console
> webdev build
Crash when formatting: [AsciiControlCharacter] The control character U+001E can only be used in strings and comments.
RangeError (index): Invalid value: Not in range 0..269138, inclusive: 272160
#0      _StringBase.[] (dart:core/runtime/libstring_patch.dart:233:55)
#1      Source.getTextLine (package:kernel/ast.dart:5772:42)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:27:9)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:80:27)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:206:32)
#5      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:215:22)
#6      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:67:13)
#7      Loader.addMessage (package:front_end/src/fasta/loader.dart:258:20)
#8      Loader.addCompileTimeError (package:front_end/src/fasta/loader.dart:207:5)
#9      LibraryBuilder.addCompileTimeError (package:front_end/src/fasta/builder/library_builder.dart:89:12)
#10     SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:174:17)
<asynchronous suspension>
#11     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:192:26)
<asynchronous suspension>
#12     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:176:13)
<asynchronous suspension>
#13     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:237:20)
<asynchronous suspension>
#14     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:232:24)
<asynchronous suspension>
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:46)
#16     new Future.sync (dart:async/future.dart:222:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:19)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117:12)
#23     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:102:20)
<asynchronous suspension>
#24     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:38:44)
<asynchronous suspension>
#25     IncrementalCompilerWrapper.compileInternal (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/vm/bin/kernel_service.dart:158:28)
<asynchronous suspension>
#26     Compiler.compile.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/vm/bin/kernel_service.dart:132:39)
#27     new Future.<anonymous closure> (dart:async/future.dart:174:37)
#28     _rootRun (dart:async/zone.dart:1122:38)
#29     _CustomZone.run (dart:async/zone.dart:1023:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#35     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#36     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#37     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

Crash when compiling file:///Users/chalin/.pub-cache/global_packages/webdev/bin/webdev.dart.snapshot,
at character offset 265550:
RangeError (index): Invalid value: Not in range 0..269138, inclusive: 272160
#0      _StringBase.[] (dart:core/runtime/libstring_patch.dart:233:55)
#1      Source.getTextLine (package:kernel/ast.dart:5772:42)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:27:9)
...
```

Related: https://github.com/dart-lang/sdk/issues/33558

**Comment by chalin** [comment] 2018-06-21 19:15
cc @kwalrath @kevmoo

**Comment by formatCvt** [comment] 2018-06-21 20:06
same error on linux

**Comment by kevmoo** [comment] 2018-06-21 20:08
@jakemac53 @natebosch – thoughts?

**Comment by natebosch** [comment] 2018-06-21 20:09
This is a duplicate of https://github.com/dart-lang/pub/issues/1932

No `pub global activate` executables work

**Closed by natebosch** 2018-06-21 20:09 UTC

**Comment by chalin** [comment] 2018-06-21 20:33
> No pub global activate executables work

Hmm, I just tried

```terminal
> pub global run webdev build
```

and it works, but `webdev build` doesn't.

**Comment by kevmoo** [comment] 2018-06-21 20:35
activate works, but the executables don't 😢
