### ISSUE TITLE
"Invalid remote object id" when calling getObject for the date class

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#773] opened 2019-10-23 11:48 UTC
The class references for DateTime's look like this:

```js
{
	"type": "@Class",
	"id": "dart:core:DateTime",
	"name": "DateTime"
},
```

But if I try to call `getObject()` for that class, I get an error:

```js
{
	"id": "477",
	"method": "getObject",
	"params": {
		"isolateId": "1",
		"objectId": "dart:core:DateTime"
	}
}
```

```
WipError 1453: {code: -32000, message: Invalid remote object id}
#0      AppInspector.jsCallFunctionOn (package:dwds/src/debugging/inspector.dart:176:9)
<asynchronous suspension>
#1      ClassMetaData.metaDataFor (package:dwds/src/debugging/metadata.dart:64:36)
<asynchronous suspension>
#2      InstanceHelper.instanceFor (package:dwds/src/debugging/instance.dart:74:40)
<asynchronous suspension>
#3      AppInspector.getObject (package:dwds/src/debugging/inspector.dart:310:24)
<asynchronous suspension>
#4      ChromeProxyService.getObject (package:dwds/src/services/chrome_proxy_service.dart:300:19)
#5      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:1027:51)
<asynchronous suspension>
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
```

We use this in VS Code to get a list of the getters to call (I don't think I can invoke the getters yet, since `evaluate` doesn't work and `invoke` can't do getters, but this seems like a bug that would need fixing for that to work).

**Comment by devoncarew** [comment] 2019-10-24 21:49
fwiw, I'm seeing this from IntelliJ as well.

**Comment by devoncarew** [comment] 2019-10-25 20:59
For help with prioritization, this is the main blocker for IntelliJ debugging now. When we have a fix for this, it would be worth it to accelerate it through the package:dwds publish -> roll into flutter/flutter process (in order to flush out any follow on problems this issue may be masking).

**Comment by grouma** [comment] 2019-10-25 21:11
I have a strong understanding of what needs to get done here. It unfortunately will take some time to resolve as it isn't exactly easy.

**Comment by devoncarew** [comment] 2019-10-25 21:36
Thanks@ I'm going to attach some service protocol traffic from IntelliJ, just to help confirm whether this is the same issue.

[traffic.txt](https://github.com/dart-lang/webdev/files/3773894/traffic.txt)

**Comment by devoncarew** [comment] 2019-10-25 21:41
In that traffic dump, there are two `message: Invalid remote object id` errors; one seems to be for when we try and retrieve more info about the `this` object when paused.

**Comment by grouma** [comment] 2019-10-25 22:57
Took a quick look at the traffic dump and the exceptions you are seeing are directly related to this issue.

The problem is that we now lazily construct metadata for libraries, which in turn sets up meta data for classes. It looks like most users of the VM service protocol do not call `getLibrary` so whenever they call `getObject` for a `ClassRef` we likely haven't initialized the meta data. This causes us to do some silly stuff and report the `Invalid remote object id` error.

The fix is pretty straightforward but will require a decent refactor. We need to change the IDs for classes so that we can do a lazy eval to get the necessary meta data without relying on a corresponding `getLibrary` call.

**Closed** 2019-10-28 22:50 UTC
Labels: bug, customer-flutter, p1, package:dwds

**Comment by DanTup** [comment] 2019-10-29 08:47
Looks good using latest code, thanks!

**Comment by DanTup** [comment] 2019-10-29 10:39
I found an issue that might be related to this one, but for bool values - I opened a new issue at https://github.com/dart-lang/webdev/issues/789.

**Comment by octav8us** [comment] 2022-12-10 11:07
what can i do if i,m still facing the same issue on IntelliJ debugger?

**Comment by DanTup** [comment] 2022-12-10 16:03
@octav8us this issue is fairly old and was fixed some time ago. If you're seeing what seems like the same issue I would verify you're on a recent version of the SDK and if so, file a new issue with instructions to reproduce.
