### ISSUE TITLE
Bump vm_service

### ISSUE THREAD

**Issue by dnfield** [dart-lang/webdev#899] opened 2020-02-13 00:01 UTC
Flutter would like to consume v2.3.1 to make tests better.

Rigth now, dwds is pinned to 1.2.0.  Per comments in #896 it's not possible to just unpin, but it should be possible to upgrade.

**Comment by jakemac53** [comment] 2020-02-13 19:01
I can take a look

**Comment by jakemac53** [comment] 2020-02-13 19:23
nevermind gary was already doing it :rofl:

**Comment by dnfield** [comment] 2020-02-13 20:58
It seems like having the dependency chain working the way it does today is going to lead to problems.

As another wild idea: perhaps dwds could avoid depending on vm_service package at all.  Other packages that depend on dwds could then use whatever version of vm_service they want, and dwds just effectively copies the source of vm_service at times where it is ready.

**Comment by jakemac53** [comment] 2020-02-13 21:35
Generally yes I would agree pinning deps is bad practice, although in this case it is working as intended. As implementors of the vm service protocol we need to know when it changes in any way, so there is a necessary coupling there. Any number of "non-breaking" changes would in fact break us.

In this case it wasn't the pinning which actually caused the problem, it was the breaking change which took us a while to update to (primarily for lack of a need to update and the fact that it was fairly breaking for us).

We are committed to responding in a timely fashion to requests to update to the latest vm_service versions.

**Closed** 2020-02-13 23:41 UTC
