### ISSUE TITLE
webdev fails with stable SDK

### ISSUE THREAD

**Issue by mnordine** [dart-lang/webdev#2288] opened 2023-11-09 00:30 UTC
Just got this with Dart 3.1.5 SDK:  
```
$ dart pub global activate webdev
00:07
Package webdev is currently active at version 3.0.7+1.
Resolving dependencies...
> build_daemon 4.0.1 (was 4.0.0)
  dds 2.11.1 (3.1.0 available)
  dds_service_extensions 1.6.0 (1.6.2 available)
  devtools_shared 4.0.1 (6.0.1 available)
  dwds 19.0.2+1 (22.1.0 available)
  file 6.1.4 (7.0.0 available)
  http 0.13.6 (1.1.0 available)
  uuid 3.0.7 (4.2.1 available)
  vm_service 11.10.0 (13.0.0 available)
  webdev 3.0.7+1 (3.2.0 available)
Building package executables...
Built webdev:webdev.
Installed executable webdev.
Activated webdev 3.0.7+1.
```

```
$ webdev build
00:30
[INFO] Reading cached asset graph completed, took 568ms
[INFO] Checking for updates since last build completed, took 1.4s
[INFO] Unhandled exception:
Instance of 'MissingPortFile'
#0      _existingPort (package:build_daemon/client.dart:24:37)
<asynchronous suspension>
dart-lang/sdk#1      BuildDaemonClient.connect (package:build_daemon/client.dart:180:9)
<asynchronous suspension>
dart-lang/sdk#2      BuildCommand.run (package:webdev/src/command/build_command.dart:66:20)
<asynchronous suspension>
dart-lang/sdk#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
dart-lang/sdk#4      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:12)
<asynchronous suspension>
dart-lang/sdk#5      run (package:webdev/src/webdev_command_runner.dart:19:46)
<asynchronous suspension>
```

_Originally posted by @mnordine in https://github.com/dart-lang/sdk/issues/53459#issuecomment-1802964621_

**Comment by elliette** [comment] 2023-11-09 01:13
Hi @mnordine! What Dart version are you on?

**Comment by mnordine** [comment] 2023-11-09 01:20
> Just got this with Dart 3.1.5 SDK

**Comment by mnordine** [comment] 2023-11-09 13:06
Entire company is stalled on this, major deploy from yesterday delayed in CI. Any workarounds?

**Comment by mnordine** [comment] 2023-11-09 14:02
I figured it out with `dart run build_runner build` for now.

**Comment by elliette** [comment] 2023-11-09 17:37
Glad you got it working! I'm unable to reproduce with the WebDev 3.0.7+1 and Dart 3.1.5 (build completes successfully, see below), so I'm going to close this issue. 

```
[INFO] Building new asset graph completed, took 1.0s
[INFO] Checking for unexpected pre-existing outputs. completed, took 0ms
[INFO] build_web_compilers:entrypoint on web/main.dart: Running `dart compile js` with --minify --libraries-spec=/Users/elliottbrooks/.dart-sdks/3.1.5/lib/libraries.json --packages=org-dartlang-app:///.dart_tool/package_config.json --multi-root-scheme=org-dartlang-app --multi-root=/private/var/folders/wy/0pdp3vd16xv2q3d5dfqb1x7400lsm6/T/scratch_spaceVwGVCu/ -oweb/main.dart.js org-dartlang-app:///web/main.dart
[INFO] build_web_compilers:entrypoint on web/main.dart: Compiled 9,793,490 input bytes (5,006,178 characters source) to 50,659 characters JavaScript in 0.79 seconds using 200.750 MB of memory

[INFO] Running build completed, took 1.7s
[INFO] Caching finalized dependency graph completed, took 135ms
[INFO] Creating merged output dir `build` completed, took 13ms
[INFO] Writing asset manifest completed, took 1ms
[INFO] Succeeded after 1.9s with 7 outputs (1753 actions)
```

**Closed by elliette** 2023-11-09 17:37 UTC

**Comment by mnordine** [comment] 2023-11-09 17:55
I was able to "fix" it locally on my machine by `dart pub upgrade`, and the transitive dep `build_daemon` went from `4.0.0` to `4.0.1`.

Seems to have worked after that.
