### ISSUE TITLE
Runtime error after upgrade

### ISSUE THREAD

**Issue by bwmalone** [dart-lang/webdev#1147] opened 2020-10-14 06:03 UTC
Previously operational project - - now crashes on start.
noSuchmethodError: method not found: 'get$digestPath'

 Please See attached log.
[localhost-1602655130598.log](https://github.com/dart-lang/webdev/files/5375933/localhost-1602655130598.log)

**Comment by mandersson1024** [comment] 2020-10-14 07:25
I get a similar error. However, I didn't upgrade anything. It worked yesterday.

**Comment by bwmalone** [comment] 2020-10-14 16:13
Glad to know I'm not the only one. After a bit of exploring, it seems that it works fine on non-chromium browsers (FF), and works in Chrome if I use profile instead of run or debug.

My google-fu has also turned up that it's an issue in certain versions of Chrome (supposedly doesn't happen on v83, but does happen on later versions), but not yet a solution. Hoping someone can shed more light.

**Comment by grouma** [comment] 2020-10-14 16:59
This is a dupe of https://github.com/dart-lang/webdev/issues/1133

I believe you just need to upgrade your SDK.

**Closed by grouma** 2020-10-14 16:59 UTC
