### ISSUE TITLE
Unhandled error detected in the injected client.js script

### ISSUE THREAD

**Issue by marcckku** [dart-lang/webdev#1144] opened 2020-10-11 22:24 UTC
NoSuchMethodError: method not found: 'get$digestsPath' (J.getInterceptor$x(...).get$digestsPath is not a function)
TypeError: J.getInterceptor$x(...).get$digestsPath is not a function
    at Object.get$digestsPath$x (http://localhost:61724/dwds/src/injected/client.js:3507:43)
    at http://localhost:61724/dwds/src/injected/client.js:22732:60
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:61724/dwds/src/injected/client.js:3802:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:61724/dwds/src/injected/client.js:10996:12)
    at Object._asyncStartSync (http://localhost:61724/dwds/src/injected/client.js:3766:20)
    at RequireRestarter._getDigests$0 (http://localhost:61724/dwds/src/injected/client.js:22744:16)
    at http://localhost:61724/dwds/src/injected/client.js:22759:48
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:61724/dwds/src/injected/client.js:3802:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:61724/dwds/src/injected/client.js:10996:12)
    at Object._asyncStartSync (http://localhost:61724/dwds/src/injected/client.js:3766:20)
    at RequireRestarter._initialize$0 (http://localhost:61724/dwds/src/injected/client.js:22767:16)
    at http://localhost:61724/dwds/src/injected/client.js:8572:45
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:61724/dwds/src/injected/client.js:3802:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:61724/dwds/src/injected/client.js:10996:12)
    at Object._asyncStartSync (http://localhost:61724/dwds/src/injected/client.js:3766:20)
    at Object.RequireRestarter_create (http://localhost:61724/dwds/src/injected/client.js:8584:16)
    at http://localhost:61724/dwds/src/injected/client.js:22319:38
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:61724/dwds/src/injected/client.js:3802:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:61724/dwds/src/injected/client.js:10996:12)
    at _awaitOnObject_closure.call$1 (http://localhost:61724/dwds/src/injected/client.js:10982:32)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:61724/dwds/src/injected/client.js:4130:18)
    at _CustomZone.runUnary$2$2 (http://localhost:61724/dwds/src/injected/client.js:12301:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:61724/dwds/src/injected/client.js:11362:51)
    at Object._Future__propagateToListeners (http://localhost:61724/dwds/src/injected/client.js:3914:93)
    at _Future._complete$1 (http://localhost:61724/dwds/src/injected/client.js:11186:11)
    at Object._cancelAndValue (http://localhost:61724/dwds/src/injected/client.js:4069:16)
    at Stream_first_closure0.call$1 (http://localhost:61724/dwds/src/injected/client.js:11454:9)
    at _EventStreamSubscription_onData_closure.call$1 (http://localhost:61724/dwds/src/injected/client.js:17309:30)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:61724/dwds/src/injected/client.js:4136:16)
    at _CustomZone.runUnary$2$2 (http://localhost:61724/dwds/src/injected/client.js:12301:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:61724/dwds/src/injected/client.js:12233:14)
    at _CustomZone_bindUnaryCallbackGuarded_closure.call$1 (http://localhost:61724/dwds/src/injected/client.js:12436:25)
    at invokeClosure (http://localhost:61724/dwds/src/injected/client.js:1204:26)
    at EventSource.<anonymous> (http://localhost:61724/dwds/src/injected/client.js:1223:18)

**Comment by cooler-king** [comment] 2020-10-12 12:59
I'm seeing the same error.

**Comment by marcckku** [comment] 2020-10-12 13:13
Hi cooler-king , yes I get this error when I want to run my flutter web app. 
Saturday 10 October it worked fine, after turning off the computer and 
accessing it again now it doesn't work anymore !! .

I tried to create my application from scratch ( https://flutter.dev/docs/get-started/web ):

 flutter channel beta
 flutter upgrade
 flutter config --enable-web

 flutter create mywebapp
 cd mywebapp

Nothing, nada de nada, nothing !!!

I don't know what I can do !!!!!

**Comment by cooler-king** [comment] 2020-10-12 13:16
Mine is an Angular Dart webapp served via webdev.

I can get it to work by doing a release build and serving that instead.  No errors in that scenario.  
The development build completes but throws this error when I run the app.

**Comment by marcckku** [comment] 2020-10-12 13:37
Maybe webdev somehow connects remotely with github and there is some inequality, I don't know !!

**Comment by marcckku** [comment] 2020-10-12 14:28
This similary problem  https://github.com/dart-lang/webdev/issues/625    but I don't understand what need to do ...

**Comment by grouma** [comment] 2020-10-12 16:16
Dupe of https://github.com/dart-lang/webdev/issues/1133

**Closed by grouma** 2020-10-12 16:16 UTC
