### ISSUE TITLE
running with different base href causes crash during connection

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/webdev#1227] opened 2021-01-20 19:47 UTC
```
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run -d chrome

## exception

StateError: Bad state: No element


#0      List.last (dart:core-patch/growable_array.dart:337:5)
#1      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:90:35)
<asynchronous suspension>
#2      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:156:5)
<asynchronous suspension>
#3      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:188:18)
<asynchronous suspension>
```

To reproduce `flutter create` a new app, and change the base href in `web/index.html` from `/` to `/foo/`.

**Comment by grouma** [comment] 2021-01-20 23:15
This seems to be a dupe of https://github.com/flutter/flutter/issues/69964

**Closed by grouma** 2021-01-20 23:15 UTC
