### ISSUE TITLE
Less eager building for webdev serve

### ISSUE THREAD

**Issue by bergwerf** [dart-lang/webdev#201] opened 2019-03-13 11:47 UTC
I'm used to hitting Ctrl+S quite often (it gives a feeling of comfort and closure :P), however this also triggers `webdev serve`. Unfortunately my T430 cannot handle all these CPU peeks without maxing the fan. However, almost all of those builds are not used. I am just writing code and I am only testing after a while. I could re-train my saving reflex but I would certainly prefer a webdev option that enables less eager building :P. Using webdev build is not an option given the huge startup time (half a minute?).

I didn't see an issue for this yet so I am submitting one. Some suggestions for alternative build tiggers:
+ The developer reloads the application page
+ The application window/tab receives focus (so the page is either hot/live/manually reloaded)
+ Custom hook (TCP port, abuse SIGALRM or similar, ...) that allows implementing your own logic (VS code plugin that rebuilds via a shortcut or when the window unfocusses, ...)

I look forward to a feature in this direction. In the meantime I will try to save less and develop code while not running webdev :)

**Comment by jakemac53** [comment] 2019-03-13 13:56
As you have sort of highlighted here already the issue is mostly deciding what alternate schemes for triggering builds are appropriate, there are a lot of potential options and it isn't clear what is worth supporting.

The build command is essentially the intended workaround, but its true that it is quite slow to start in the current webdev because it doesn't support build script snapshots, so its recompiling the build script every time which is quite slow. However, with the webdev 2.0 release we are moving to use the new build daemon, which will use snapshots and share builds across tools, and that should speed things up a ton.

If you would like to try that out you can global activate webdev from the master branch of this repo and see how that works for you, it should be much better (not that global activating via path means webdev itself won't run from snapshot though).

**Comment by jakemac53** [comment] 2019-03-13 13:57
You can also try running with --low-resources-mode which will drop it to one worker per task and reduce memory consumption.

**Comment by natebosch** [comment] 2019-03-13 22:41
This would be more difficult to implement now that we're using the `build_daemon` protocol.

@grouma - do you have any thoughts on whether it would be appropriate to extend the protocol so that the client can trigger builds?

**Comment by grouma** [comment] 2019-03-14 00:52
The protocol already supports triggering builds and we make use of that feature today. What we don't support is for a way to tell the build_daemon to ignore edits until a trigger occurs.

**Comment by bergwerf** [comment] 2019-03-14 03:11
@jakemac53 It looks like `--low-resources-mode` is not supported by webdev 1.0.0 (--version reports 1.0.0 but pub global activate reports 1.0.1)

**Comment by bergwerf** [comment] 2019-03-14 03:18
Also, I cloned the repository to activate the latest webdev and got `Unable to spawn isolate: webdev/lib/src/serve/handlers/dev_handler.dart:10:8: Error: Error when reading 'webdev/dwds/lib/service.dart': No such file or directory`. But I suppose that's more a question for another place.

**Comment by grouma** [comment] 2019-03-14 03:24
We are in the process of making major changes to WebDev so running from head requires some special setup, e.g. using the edge SDK. You can safely ignore that issue.

**Comment by jakemac53** [comment] 2019-03-14 14:19
> @jakemac53 It looks like `--low-resources-mode` is not supported by webdev 1.0.0 (--version reports 1.0.0 but pub global activate reports 1.0.1)

Oh right I don't think webdev itself supports that flag :/

**Comment by grouma** [comment] 2019-08-21 17:50
This should be resolved by the debounce logic: https://github.com/dart-lang/build/pull/2412

If that doesn't work we also now have a manual build mode which we can consider exposing in webdev.

**Closed by grouma** 2019-08-21 17:50 UTC
