### ISSUE TITLE
StateError: Bad state: No element

### ISSUE THREAD

**Issue by zanderso** [dart-lang/webdev#693] opened 2019-10-01 20:31 UTC
From flutter tool crash logging during an invocation of `run -d chrome`.

```
StateError: Bad state: No element
  | at Stream.first.<anonymous closure> | (stream.dart:1254 )
  | at _rootRun | (zone.dart:1120 )
  | at _CustomZone.run | (zone.dart:1021 )
  | at _CustomZone.runGuarded | (zone.dart:923 )
  | at _DoneStreamSubscription._sendDone | (stream_impl.dart:778 )
  | at _rootRun | (zone.dart:1124 )
  | at _CustomZone.run | (zone.dart:1021 )
  | at _CustomZone.runGuarded | (zone.dart:923 )
  | at _CustomZone.bindCallbackGuarded.<anonymous closure> | (zone.dart:963 )
  | at _microtaskLoop | (schedule_microtask.dart:41 )
  | at _startMicrotaskLoop | (schedule_microtask.dart:50 )
  | at _runPendingImmediateCallback | (isolate_patch.dart:116 )
  | at _RawReceivePortImpl._handleMessage | (isolate_patch.dart:173 )
```

Sorry there's not a lot to go on here. This is the sort of thing where webdev using a Zone internally or making sure there aren't any dropped Futures would make this easier to track down.

/cc @jakemac53

**Comment by jakemac53** [comment] 2019-10-01 21:08
We can look at where we call `Stream.first`, I don't think it should happen much as that is generally a code smell.

Could this potentially be coming from the flutter tool as well? We do expose a couple streams. 

Fwiw in general it isn't that we are dropping futures or not awaiting futures - the problem is we are responding to other async events (usually from a websocket/sse channel). Any errors that happen as a result of handling those events will always end up as unhandled async errors and so the only way to handle them is with a Zone.

**Comment by zanderso** [comment] 2019-10-01 21:18
Yeah, it may be in the Flutter tool. I found this use:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_runner/web_fs.dart#L134

@jonahwilliams

**Comment by jakemac53** [comment] 2019-10-02 14:22
Actually that one link seems likely - it would be fairly likely to never get an event. In the extension mode I believe we would only get a connection if/when the user actually initiates debugging by clicking the extension icon.

In the regular (direct chrome connection) mode we would always get an event as soon as the app starts up.

**Comment by grouma** [comment] 2019-10-15 16:42
Seems like the root cause resides outside this package. Closing. Please re-open if you need work on our end.

**Closed by grouma** 2019-10-15 16:42 UTC
Labels: bug, customer-flutter
